export const structure = (S: any) =>
  S.list()
    .title("Content")
    .items([
      S.listItem()
        .title("Services")
        .id("servicesPage")
        .child(
          S.document().schemaType("servicesPage").documentId("servicesPage"),
        ),
      S.listItem()
        .title("References")
        .id("referencesPage")
        .child(
          S.document()
            .schemaType("referencesPage")
            .documentId("referencesPage"),
        ),
      S.listItem()
        .title("Terms")
        .id("termsPage")
        .child(S.document().schemaType("termsPage").documentId("termsPage")),
      S.listItem()
        .title("Imprint")
        .id("impressumPage")
        .child(
          S.document().schemaType("impressumPage").documentId("impressumPage"),
        ),
    ]);
